version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: wellpump-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wellpump
      POSTGRES_USER: wellpump
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - wellpump

  app:
    build: .
    container_name: wellpump-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://wellpump:${DB_PASSWORD:-secure_password_change_me}@db:5432/wellpump?schema=public"
      NEXTAUTH_URL: "${NEXTAUTH_URL:-http://localhost:3000}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET:-your-secret-key-here}"
      DATA_RETENTION_YEARS: "${DATA_RETENTION_YEARS:-3}"
      INTERNAL_API_KEY: "${INTERNAL_API_KEY:-internal-api-key-change-me}"
      VAPID_PUBLIC_KEY: "${VAPID_PUBLIC_KEY:-}"
      VAPID_PRIVATE_KEY: "${VAPID_PRIVATE_KEY:-}"
      PUSHOVER_TOKEN: "${PUSHOVER_TOKEN:-}"
      PUSHOVER_USER: "${PUSHOVER_USER:-}"
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - wellpump

  nginx:
    image: nginx:alpine
    container_name: wellpump-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - wellpump

networks:
  wellpump:
    driver: bridge

volumes:
  postgres_data:
    driver: local